#spring:
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/GeoTrackDB
#      mapping:
#        type-key: null
#server:
#  port: 8097

spring:

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/fleet-management-system

  data:
    mongodb:
      uri: mongodb://localhost:27017/GeoTrackDB
      mapping:
        type-key: null

feign-client-user-service:
  base-url: http://localhost:8093/api/organizations

app:
  cors:
    allowed-origins:
      - http://localhost:5173

