#spring:
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/GeoTrackDB
#      mapping:
#        type-key: null
#server:
#  port: 8097

spring:
  application:
    name: driver-service



jwt:
  auth:
    converter:
      resource-id: fleet-management-system
      principal-attribute: preferred_username



logging:
  level:
    org.springframework.security: DEBUG

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka}

server:
  port: 8097