server:
  port: 8222

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true  # Recommended for consistency

      routes:
        - id: vehicle-service
          uri: lb://VEHICLE-SERVICE
          predicates:
            - Path=/api/v1/vehicles/**
#          filters:
#            - RewritePath=/api/v1/vehicles/(?<remaining>.*), /$\{remaining}

        - id: tracker-service
          uri: lb://TRACKER-SERVICE
          predicates:
            - Path=/api/v1/trackers/**
#          filters:
#            - RewritePath=/api/v1/trackers/(?<remaining>.*), /$\{remaining}

        - id: driver-service
          uri: lb://DRIVER-SERVICE
          predicates:
            - Path=/api/v1/drivers/**
#          filters:
#            - RewritePath=/api/v1/drivers/(?<remaining>.*), /$\{remaining}

        - id: position-service
          uri: lb://POSITION-SERVICE
          predicates:
            - Path=/api/v1/positions/**
#          filters:
#            - RewritePath=/api/v1/positions/(?<remaining>.*), /$\{remaining}

        - id: minio-service
          uri: lb://MINIO-SERVICE
          predicates:
            - Path=/minio/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/userextras/**

        - id: organizations
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/organizations/**

#          filters:
#            - RewritePath=/api/userextras/(?<remaining>.*), /$\{remaining}

        - id: subscription-service
          uri: lb://SUBSCRIPTION-SERVICE
          predicates:
            - Path=/api/v1/{segment:subscription|payment}/**
#          filters:
#            - RewritePath=/api/v1/(?<segment>subscription|payment)/(?<remaining>.*), /$\{remaining}
        - id: alert-service
          uri: lb://ALERT-SERVICE
          predicates:
            - Path=/api/v1/alerts/**

jwt:
  auth:
    converter:
      resource-id: fleet-management-system
      principal-attribute: preferred_username



logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
    org.springframework.web: DEBUG