spring:
  data:
    mongodb:
      uri: mongodb://45.10.162.39:21212/GeoTrackDB
      mapping:
        type-key: null

  services:
    subscription: http://45.10.162.39:8089/api/v1/subscription

  security:
    oauth2:
      resourceserver:
        jwt:
          # The Keycloak public key URI for JWT validation
#          issuer-uri: https://45.10.162.39:8443/realms/fleet-management-system
          issuer-uri: https://geotrackify.com/auth/realms/fleet-management-system


app:
  cors:
    allowed-origins: "*"


