spring:
  application:
    name: user-service

jwt:
  auth:
    converter:
      resource-id: fleet-management-system
      principal-attribute: preferred_username
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka}

#user-service:
#  base-url: http://localhost:8093/api


server:
  port: 8093
