
spring:

  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: alert-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    #      properties:
    #        spring.json.trusted.packages: "*"
    #        spring.json.type.mapping: AlertVehicle:com.fleetManagementSystem.commons.alert.AlertVehicle

    #    listener:
    #      type: batch # Optional, if you want to handle messages in batches

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: AlertVehicle:com.fleetManagementSystem.commons.alert.AlertVehicle

#    bootstrap-servers: localhost:9092 # Kafka broker address

  data:
    mongodb:
      uri: mongodb://localhost:27017/GeoTrackDB
      mapping:
        type-key: null


feign-client-vehicles-service:
  base-url: http://localhost:8091